b=imread('01_test.tif');
a=rgb2gray(b);
bit1=bitget(a,1);
figure,imshow(bit1,[])
bit2=bitget(a,2);
figure,imshow(bit2,[])
bit3=bitget(a,3);
figure,imshow(bit3,[])
bit4=bitget(a,4);
figure,imshow(bit4,[])
bit5=bitget(a,5);
figure,imshow(bit5,[])
bit6=bitget(a,6);
figure,imshow(bit6,[])
bit7=bitget(a,7);
figure,imshow(bit7,[])
bit8=bitget(a,8);
figure,imshow(bit8,[])
